[package]
name = "web"
version = "0.1.0"
edition = "2021"

[dependencies]
leptos = { version = "0.8", features = ["csr"] }
leptos-use = "0.16"
codee = "0.3"
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["preserve_order"] }
shared = { path = "../shared" }
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
js-sys = "0.3"
gloo-file = { version = "0.3", features = ["futures"] }
console_error_panic_hook = "0.1"

[dependencies.web-sys]
version = "0.3"
features = [
  "Window",
  "Document",
  "Element",
  "HtmlElement",
  "Node",
  "CssStyleDeclaration",
  "HtmlInputElement",
  "HtmlAnchorElement",
  "File",
  "FileList",
  "Blob",
  "BlobPropertyBag",
  "Url",
  "Event",
]
